# Change these first
owner: ElenaMLopez # Your GitHub organization or username, where this repository lives
repo: holafly-status-page # The name of this repository

sites:
  - name: Holafly e-commerce web
    url: https://esim.holafly.com
  - name: Shortener
    url: https://holaf.ly
  - name: Activaciones
    url: https://activaciones.holafly.co
  #- name: Test Broken Site
  #  url: https://thissitedoesnotexist.koj.co
  #- name: IPv6 test
  #  url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /holafly-status-page
  logoUrl: https://tzgvp7n8bz3v-u4239.pressidiumcdn.com/es/wp-content/themes/Holafly_v2-child/recursos/img/H.svg
  name: Holafly Status
  introTitle: "Here you can see the Holafly services and pages status"
  introMessage: You can check details in each incident if you want. This page is automatically updated every 10 minutes.
  navbar:
    - title: Status
      href: https://$OWNER.github.io/holafly-status-page
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
